### ISSUE TITLE
RCON Console color

### ISSUE THREAD

**Issue by lechuga16** [aXenDeveloper/sourcebans-web-theme-fluent#9]
Hello, I was using your work and I congratulate you, it is very well done. But there is an important detail when using the dark theme regarding the color of the rcon console, the letters are white and the background as well, so I modified the following line

https://github.com/aXenDeveloper/sourcebans-web-theme-fluent/blob/f2ade5bae822ebedf6ccba83daf3b5c02057a318/sourcebans-web-theme-fluent/page_admin_servers_rcon.tpl#L22

by the following code 'background-color:#171717;'

It is a solution that I want to share with you, thank you.
![Screenshot_2](https://user-images.githubusercontent.com/34782281/127780342-57355ede-d3ec-4c40-ae92-a2b91eb7879d.png)

**Comment by aXenDeveloper** [comment]
Where is this console?

**Comment by lechuga16** [comment]
displayed only if user has rcon access.

![Screenshot_3](https://user-images.githubusercontent.com/34782281/127947863-0645c8ff-30c2-42a3-ac7d-73924388281e.png)

**Comment by crashzk** [comment]
I think it's better to change the font color, since whoever uses the light theme to change the console background would change it too.
![image](https://user-images.githubusercontent.com/32937653/128247750-0b3856a4-bc26-416e-a4de-18ed1c3cbf38.png)

![image](https://user-images.githubusercontent.com/32937653/128247772-f97857b2-6912-4f97-99e1-bd79f113e5ad.png)

**Comment by aXenDeveloper** [comment]
Fixed in https://github.com/aXenDeveloper/sourcebans-web-theme-fluent/pull/22
![image](https://user-images.githubusercontent.com/58148176/130242816-db19a598-f701-41a9-a583-32cc58a133b6.png)
![image](https://user-images.githubusercontent.com/58148176/130242840-e3287058-109e-46a9-bc1e-567711b4739c.png)
